title: Flickr-cropping-dataset
description: Dataset that contains photos crawled from Flickr and annotations that indicates a local window representing a good composition.
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
