title: Flickr Cropping Dataset
description: Quantitative Analysis of Automatic Image Cropping Algorithms: A data set and comparative study.
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
