title: Quantitative Analysis of Automatic Image Cropping Algorithms
description: A data set and comparative study.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
